// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 
module axis_ip_top (
  input         clk,
  input         reset,
  input  [31:0] din,
  input         vld_in,
  output        rdy_in,
  output [31:0] dout,
  output        vld_out,
  input         rdy_out,
  output [3:0]  keep_out,
  output        last_out
);


endmodule

